insert into poll (published_at, question, id) values ('2015-08-05T08:40:51.620Z', 'Favourite programming language?', 1)
insert into poll_choices (poll_id, choice, votes) values (1, 'Swift', 256)
insert into poll_choices (poll_id, choice, votes) values (1, 'Python', 1024)
insert into poll_choices (poll_id, choice, votes) values (1, 'Objective-C', 512)
insert into poll_choices (poll_id, choice, votes) values (1, 'Ruby', 256)
